### ISSUE TITLE
[Bug]: cannot import name 'has_torch2' from 'modelscope.t2v_model

### ISSUE THREAD

**Issue by SnikeGear** [kabachuha/sd-webui-text2video#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

Error loading script: api_t2v.py
Traceback (most recent call last):
  File "C:\pt3106\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\pt3106\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\pt3106\stable-diffusion-webui\extensions\sd-webui-text2video\scripts\api_t2v.py", line 35, in <module>
    from t2v_helpers.args import T2VArgs_sanity_check, T2VArgs, T2VOutputArgs
  File "C:\pt3106\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\t2v_helpers\args.py", line 7, in <module>
    from modelscope.t2v_model import has_torch2
ImportError: cannot import name 'has_torch2' from 'modelscope.t2v_model' (C:\pt3106\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\modelscope\t2v_model.py)

Error loading script: text2vid.py
Traceback (most recent call last):
  File "C:\pt3106\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\pt3106\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\pt3106\stable-diffusion-webui\extensions\sd-webui-text2video\scripts\text2vid.py", line 20, in <module>
    from t2v_helpers.render import run
  File "C:\pt3106\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\t2v_helpers\render.py", line 5, in <module>
    from modelscope.process_modelscope import process_modelscope
  File "C:\pt3106\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\modelscope\process_modelscope.py", line 21, in <module>
    from t2v_helpers.args import get_outdir, process_args
  File "C:\pt3106\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\t2v_helpers\args.py", line 7, in <module>
    from modelscope.t2v_model import has_torch2
ImportError: cannot import name 'has_torch2' from 'modelscope.t2v_model' (C:\pt3106\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\modelscope\t2v_model.py)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### WebUI and Deforum extension Commit IDs

webui commit id - e5244d4bde
txt2vid commit id - 8cba2def5b36ea496645813bb4f2223343246ff1

### Torch version

torch version 2.0.1+cu118 installed

### What GPU were you using for launching?

rtx 3060 12 gb

### On which platform are you launching the webui backend with the extension?

Local PC setup (Windows)

### Settings

@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set DREAMBOOTH_SKIP_INSTALL=True
set COMMANDLINE_ARGS=--xformers --api --no-half-vae --opt-split-attention --upcast-sampling --opt-channelslast
call webui.bat

### Console logs

```Shell
Error loading script: api_t2v.py
Traceback (most recent call last):
  File "C:\pt3106\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\pt3106\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\pt3106\stable-diffusion-webui\extensions\sd-webui-text2video\scripts\api_t2v.py", line 35, in <module>
    from t2v_helpers.args import T2VArgs_sanity_check, T2VArgs, T2VOutputArgs
  File "C:\pt3106\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\t2v_helpers\args.py", line 7, in <module>
    from modelscope.t2v_model import has_torch2
ImportError: cannot import name 'has_torch2' from 'modelscope.t2v_model' (C:\pt3106\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\modelscope\t2v_model.py)

Error loading script: text2vid.py
Traceback (most recent call last):
  File "C:\pt3106\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\pt3106\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\pt3106\stable-diffusion-webui\extensions\sd-webui-text2video\scripts\text2vid.py", line 20, in <module>
    from t2v_helpers.render import run
  File "C:\pt3106\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\t2v_helpers\render.py", line 5, in <module>
    from modelscope.process_modelscope import process_modelscope
  File "C:\pt3106\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\modelscope\process_modelscope.py", line 21, in <module>
    from t2v_helpers.args import get_outdir, process_args
  File "C:\pt3106\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\t2v_helpers\args.py", line 7, in <module>
    from modelscope.t2v_model import has_torch2
ImportError: cannot import name 'has_torch2' from 'modelscope.t2v_model' (C:\pt3106\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\modelscope\t2v_model.py)
```

**Comment by SnikeGear** [comment]
Oh nice bot. I go to delete this report and the Extension
