### ISSUE TITLE
[Bug]: On vladomatic-Automatic:'Namespace' object has no attribute 'force_enable_xformers

### ISSUE THREAD

**Issue by ShmuelRonen** [kabachuha/sd-webui-text2video#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

When running the text2 and video extension on Vladomatic-Automatic, the following error is received during startup:

File "D:\Path\SD\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 492, in forward
    if cmd_opts.force_enable_xformers or (cmd_opts.xformers and shared.xformers_available and torch.version.cuda and (6, 0) <= torch.cuda.get_device_capability(shared.device) <= (9, 0)):
AttributeError: 'Namespace' object has no attribute 'force_enable_xformers'
Exception occurred: **'Namespace' object has no attribute 'force_enable_xformers'**

**I discussed this with the developer and he wrote me the following:**

it's because extension checks cmdflags which are different. Extension should check if xformers are enabled or not, not check cmdflags from core app ever.

I cannot support extensions that do things the wrong way and hard code things that prevent any kind of change ever.

What fails is extension check of core repo command line flags - which it should never do. And that fails because flags are clearly different.

### Steps to reproduce the problem

1. Write a prompt
2. Press on execute
3. The error come...

### What should have happened?

A video

### WebUI and Deforum extension Commit IDs

webui commit id - 
txt2vid commit id -

### Torch version

C:\vlad\automatic>webui.bat
Using VENV: C:\vlad\automatic\venv
09:10:22-760205 INFO Starting SD.Next
09:10:22-764205 INFO Python 3.10.7 on Windows
09:10:22-845203 INFO Version: https://github.com/vladmandic/automatic/commit/b340e3f40c36eda26bf62fcbcdfec7219a731cea Sun Jun 18 16:30:59 2023 -0400
09:10:23-399205 INFO nVidia CUDA toolkit detected
09:10:24-626205 INFO Torch 2.0.1+cu118
09:10:24-640203 INFO Torch backend: nVidia CUDA 11.8 cuDNN 8700
09:10:24-643203 INFO Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82

### What GPU were you using for launching?

nVidia CUDA 11.8 cuDNN 8700

### On which platform are you launching the webui backend with the extension?

Local PC setup (Windows)

### Settings

Windows 10 Pro

### Console logs

```Shell
Traceback (most recent call last):                                                              | 0/20 [00:00<?, ?it/s]
  File "D:\Path\SD\automatic/extensions/sd-webui-text2video/scripts\t2v_helpers\render.py", line 27, in run
    vids_pack = process_modelscope(args_dict)
  File "D:\Path\SD\automatic/extensions/sd-webui-text2video/scripts\modelscope\process_modelscope.py", line 209, in process_modelscope
    samples, _ = pipe.infer(args.prompt, args.n_prompt, args.steps, args.frames, args.seed + batch if args.seed != -1 else -1, args.cfg_scale,
  File "D:\Path\SD\automatic/extensions/sd-webui-text2video/scripts\modelscope\t2v_pipeline.py", line 258, in infer
    x0 = self.diffusion.ddim_sample_loop(
  File "D:\Path\SD\automatic\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Path\SD\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 1485, in ddim_sample_loop
    xt = self.ddim_sample(xt, t, model, model_kwargs, clamp,
  File "D:\Path\SD\automatic\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Path\SD\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 1334, in ddim_sample
    _, _, _, x0 = self.p_mean_variance(xt, t, model, model_kwargs, clamp,
  File "D:\Path\SD\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 1275, in p_mean_variance
    y_out = model(xt, self._scale_timesteps(t), **model_kwargs[0])
  File "D:\Path\SD\automatic\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Path\SD\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 369, in forward
    x = self._forward_single(block, x, e, context, time_rel_pos_bias,
  File "D:\Path\SD\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 432, in _forward_single
    x = self._forward_single(block, x, e, context,
  File "D:\Path\SD\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 416, in _forward_single
    x = module(x, context)
  File "D:\Path\SD\automatic\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Path\SD\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 673, in forward
    x = block(x)
  File "D:\Path\SD\automatic\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Path\SD\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 740, in forward
    x = self.attn1(
  File "D:\Path\SD\automatic\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Path\SD\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 492, in forward
    if cmd_opts.force_enable_xformers or (cmd_opts.xformers and shared.xformers_available and torch.version.cuda and (6, 0) <= torch.cuda.get_device_capability(shared.device) <= (9, 0)):
AttributeError: 'Namespace' object has no attribute 'force_enable_xformers'
Exception occurred: 'Namespace' object has no attribute 'force_enable_xformers'
```

**Comment by ShmuelRonen** [comment]
> This issue has been closed due to incorrect formatting. Please address the following mistakes and reopen the issue:
> 
> * Include **THE FULL LOG FROM THE START OF THE WEBUI** in the issue description.

I do
