### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'tqdm.auto'

### ISSUE THREAD

**Issue by alienware377** [kabachuha/sd-webui-text2video#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

Webui startup failed due to some odd bug in your extension. I have tried resetting the venv folder and it same result, then removed ur extension and same result, but after removing your extension AND deleting venv folder, webui loaded with no errors. adding your extension back in resulted in the error again. 

### Steps to reproduce the problem

1. open webui-user.bat
2. starts loading then errors out and prevents continuing.

### What should have happened?

webui continue loading

### WebUI and Deforum extension Commit IDs

webui commit id - 68f336bd994bed5442ad95bad6b6ad5564a5409a
txt2vid commit id - 8f0af8c95a3c3a3af09c63cbdbdacc34b7a45f8d

### Torch version

2.0.0+cu118

### What GPU were you using for launching?

3090 TI 24gb

### On which platform are you launching the webui backend with the extension?

Local PC setup (Windows)

### Settings

wat? idk wym but here's a screenshot of my other extensions since i guess that might be helpful
![image](https://github.com/kabachuha/sd-webui-text2video/assets/126924491/c62d20eb-50c5-4216-8acd-2b7b838a00e4)

### Console logs

```Shell
Already up to date.
Creating venv in directory E:\stable-diffusion-webui\venv using python "C:\Users\Logan\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
venv "E:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Collecting torch==2.0.0+cu118
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.0%2Bcu118-cp310-cp310-win_amd64.whl (2611.3 MB)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
Collecting xformers==0.0.17
  Using cached xformers-0.0.17-cp310-cp310-win_amd64.whl (112.6 MB)
Collecting jinja2
  Using cached https://download.pytorch.org/whl/Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting filelock
  Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting networkx
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting sympy
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting numpy
  Using cached numpy-1.25.2-cp310-cp310-win_amd64.whl (15.6 MB)
Collecting pyre-extensions==0.0.23
  Using cached pyre_extensions-0.0.23-py3-none-any.whl (11 kB)
Collecting typing-inspect
  Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Collecting torchvision
  Using cached torchvision-0.15.2-cp310-cp310-win_amd64.whl (1.2 MB)
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.1%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached Pillow-10.0.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl (17 kB)
Collecting idna<4,>=2.5
  Using cached https://download.pytorch.org/whl/idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.2.0-cp310-cp310-win_amd64.whl (96 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.4-py3-none-any.whl (123 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting mypy-extensions>=0.3.0
  Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, mypy-extensions, MarkupSafe, idna, filelock, charset-normalizer, certifi, typing-inspect, requests, jinja2, torch, pyre-extensions, xformers, torchvision
Successfully installed MarkupSafe-2.1.3 certifi-2023.7.22 charset-normalizer-3.2.0 filelock-3.12.2 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 mypy-extensions-1.0.0 networkx-3.1 numpy-1.25.2 pillow-10.0.0 pyre-extensions-0.0.23 requests-2.31.0 sympy-1.12 torch-2.0.0+cu118 torchvision-0.15.1+cu118 typing-extensions-4.7.1 typing-inspect-0.9.0 urllib3-2.0.4 xformers-0.0.17

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: E:\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
Installing gfpgan
Installing clip
Installing open_clip
Installing requirements for CodeFormer
Installing requirements
Collecting ultralytics>=8.0.97
  Using cached ultralytics-8.0.150-py3-none-any.whl (614 kB)
Requirement already satisfied: torchvision>=0.8.1 in e:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.0.97) (0.15.1+cu118)
Requirement already satisfied: numpy>=1.22.2 in e:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.0.97) (1.23.5)
Requirement already satisfied: pandas>=1.1.4 in e:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.0.97) (2.0.3)
Collecting seaborn>=0.11.0
  Using cached seaborn-0.12.2-py3-none-any.whl (293 kB)
Requirement already satisfied: scipy>=1.4.1 in e:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.0.97) (1.11.1)
Collecting py-cpuinfo
  Using cached py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
Requirement already satisfied: opencv-python>=4.6.0 in e:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.0.97) (4.8.0.74)
Requirement already satisfied: matplotlib>=3.2.2 in e:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.0.97) (3.7.2)
Requirement already satisfied: psutil in e:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.0.97) (5.9.5)
Requirement already satisfied: pyyaml>=5.3.1 in e:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.0.97) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in e:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.0.97) (2.31.0)
Requirement already satisfied: torch>=1.7.0 in e:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.0.97) (2.0.0+cu118)
Requirement already satisfied: tqdm>=4.64.0 in e:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.0.97) (4.65.1)
Requirement already satisfied: pillow>=7.1.2 in e:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.0.97) (9.5.0)
Requirement already satisfied: python-dateutil>=2.7 in e:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.2.2->ultralytics>=8.0.97) (2.8.2)
Requirement already satisfied: cycler>=0.10 in e:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.2.2->ultralytics>=8.0.97) (0.11.0)
Requirement already satisfied: packaging>=20.0 in e:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.2.2->ultralytics>=8.0.97) (23.1)
Requirement already satisfied: kiwisolver>=1.0.1 in e:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.2.2->ultralytics>=8.0.97) (1.4.4)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in e:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.2.2->ultralytics>=8.0.97) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in e:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.2.2->ultralytics>=8.0.97) (1.1.0)
Requirement already satisfied: fonttools>=4.22.0 in e:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.2.2->ultralytics>=8.0.97) (4.42.0)
Requirement already satisfied: pytz>=2020.1 in e:\stable-diffusion-webui\venv\lib\site-packages (from pandas>=1.1.4->ultralytics>=8.0.97) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in e:\stable-diffusion-webui\venv\lib\site-packages (from pandas>=1.1.4->ultralytics>=8.0.97) (2023.3)
Requirement already satisfied: certifi>=2017.4.17 in e:\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.0.97) (2023.7.22)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.0.97) (1.26.16)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.0.97) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in e:\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.0.97) (3.4)
Requirement already satisfied: sympy in e:\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.7.0->ultralytics>=8.0.97) (1.12)
Requirement already satisfied: typing-extensions in e:\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.7.0->ultralytics>=8.0.97) (4.7.1)
Requirement already satisfied: networkx in e:\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.7.0->ultralytics>=8.0.97) (3.1)
Requirement already satisfied: jinja2 in e:\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.7.0->ultralytics>=8.0.97) (3.1.2)
Requirement already satisfied: filelock in e:\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.7.0->ultralytics>=8.0.97) (3.12.2)
Requirement already satisfied: colorama in e:\stable-diffusion-webui\venv\lib\site-packages (from tqdm>=4.64.0->ultralytics>=8.0.97) (0.4.6)
Requirement already satisfied: six>=1.5 in e:\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.2.2->ultralytics>=8.0.97) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in e:\stable-diffusion-webui\venv\lib\site-packages (from jinja2->torch>=1.7.0->ultralytics>=8.0.97) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in e:\stable-diffusion-webui\venv\lib\site-packages (from sympy->torch>=1.7.0->ultralytics>=8.0.97) (1.3.0)
Installing collected packages: py-cpuinfo, seaborn, ultralytics
Successfully installed py-cpuinfo-9.0.0 seaborn-0.12.2 ultralytics-8.0.150
Collecting mediapipe>=0.10.0
  Using cached mediapipe-0.10.3-cp310-cp310-win_amd64.whl (50.2 MB)
Requirement already satisfied: matplotlib in e:\stable-diffusion-webui\venv\lib\site-packages (from mediapipe>=0.10.0) (3.7.2)
Collecting opencv-contrib-python
  Using cached opencv_contrib_python-4.8.0.74-cp37-abi3-win_amd64.whl (44.8 MB)
Collecting sounddevice>=0.4.4
  Using cached sounddevice-0.4.6-py3-none-win_amd64.whl (199 kB)
Collecting flatbuffers>=2.0
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: absl-py in e:\stable-diffusion-webui\venv\lib\site-packages (from mediapipe>=0.10.0) (1.4.0)
Requirement already satisfied: numpy in e:\stable-diffusion-webui\venv\lib\site-packages (from mediapipe>=0.10.0) (1.23.5)
Requirement already satisfied: protobuf<4,>=3.11 in e:\stable-diffusion-webui\venv\lib\site-packages (from mediapipe>=0.10.0) (3.20.0)
Requirement already satisfied: attrs>=19.1.0 in e:\stable-diffusion-webui\venv\lib\site-packages (from mediapipe>=0.10.0) (23.1.0)
Collecting CFFI>=1.0
  Using cached cffi-1.15.1-cp310-cp310-win_amd64.whl (179 kB)
Requirement already satisfied: cycler>=0.10 in e:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe>=0.10.0) (0.11.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in e:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe>=0.10.0) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in e:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe>=0.10.0) (2.8.2)
Requirement already satisfied: packaging>=20.0 in e:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe>=0.10.0) (23.1)
Requirement already satisfied: kiwisolver>=1.0.1 in e:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe>=0.10.0) (1.4.4)
Requirement already satisfied: contourpy>=1.0.1 in e:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe>=0.10.0) (1.1.0)
Requirement already satisfied: fonttools>=4.22.0 in e:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe>=0.10.0) (4.42.0)
Requirement already satisfied: pillow>=6.2.0 in e:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe>=0.10.0) (9.5.0)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Requirement already satisfied: six>=1.5 in e:\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->mediapipe>=0.10.0) (1.16.0)
Installing collected packages: flatbuffers, pycparser, opencv-contrib-python, CFFI, sounddevice, mediapipe
Successfully installed CFFI-1.15.1 flatbuffers-23.5.26 mediapipe-0.10.3 opencv-contrib-python-4.8.0.74 pycparser-2.21 sounddevice-0.4.6
Collecting rich>=13.4.2
  Using cached rich-13.5.2-py3-none-any.whl (239 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in e:\stable-diffusion-webui\venv\lib\site-packages (from rich>=13.4.2) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in e:\stable-diffusion-webui\venv\lib\site-packages (from rich>=13.4.2) (2.16.1)
Requirement already satisfied: mdurl~=0.1 in e:\stable-diffusion-webui\venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.4.2) (0.1.2)
Installing collected packages: rich
Successfully installed rich-13.5.2

Installing onnx for PBRemTools
Installing onnxruntime for PBRemTools
Installing segmentation_refinement for PBRemTools
Installing sklearn for PBRemTools
Installing segment_anything for PBRemTools

Installing requirements for CivitAI Browser

Installing sd-webui-controlnet requirement: svglib
Installing sd-webui-controlnet requirement: fvcore

Installing text2video requirement: imageio_ffmpeg
Installing text2video requirement: av
Installing text2video requirement: moviepy
Installing text2video requirement: numexpr

Installing sd-webui-txt-img-to-3d-model requirement: blobfile
Installing sd-webui-txt-img-to-3d-model requirement: ipywidgets

Installing rembg
Installing pymatting for REMBG extension
Installing pooch for REMBG extension

Launching Web UI with arguments: --listen --opt-sdp-attention --opt-split-attention --no-half-vae --enable-insecure-extension-access --api --cors-allow-origins=https://www.painthua.com
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\launch.py", line 39, in <module>
    main()
  File "E:\stable-diffusion-webui\launch.py", line 35, in main
    start()
  File "E:\stable-diffusion-webui\modules\launch_utils.py", line 390, in start
    import webui
  File "E:\stable-diffusion-webui\webui.py", line 39, in <module>
    import pytorch_lightning   # noqa: F401 # pytorch_lightning should be imported after torch, but it re-enables warnings on import so import once to disable them
  File "E:\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "E:\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 22, in <module>
    from pytorch_lightning.callbacks.lr_finder import LearningRateFinder
  File "E:\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\callbacks\lr_finder.py", line 24, in <module>
    from pytorch_lightning.tuner.lr_finder import _LRFinder, lr_find
  File "E:\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\tuner\lr_finder.py", line 36, in <module>
    from tqdm.auto import tqdm
ModuleNotFoundError: No module named 'tqdm.auto'
Press any key to continue . . .
```

**Comment by alienware377** [comment]
i'm super dumb, i don't know how i didn't notice the same issue in the bug thread 2 wks ago. closing this now

**Comment by Faisalalali** [comment]
Is this fixed? I'm still getting a similar error in the latest commit on a fresh install.

<details><summary>Details</summary>
<p>

```bash
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments:
Traceback (most recent call last):
  File "C:\somewhere\sd.webui\webui\launch.py", line 48, in <module>
    main()
  File "C:\somewhere\sd.webui\webui\launch.py", line 44, in main
    start()
  File "C:\somewhere\sd.webui\webui\modules\launch_utils.py", line 432, in start
    import webui
  File "C:\somewhere\sd.webui\webui\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\somewhere\sd.webui\webui\modules\initialize.py", line 21, in imports
    import gradio  # noqa: F401
  File "C:\somewhere\sd.webui\system\python\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\somewhere\sd.webui\system\python\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\somewhere\sd.webui\system\python\lib\site-packages\gradio\components\annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
  File "C:\somewhere\sd.webui\system\python\lib\site-packages\gradio_client\__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "C:\somewhere\sd.webui\system\python\lib\site-packages\gradio_client\client.py", line 24, in <module>
    from huggingface_hub import CommitOperationAdd, SpaceHardware, SpaceStage
  File "C:\somewhere\sd.webui\system\python\lib\site-packages\huggingface_hub\__init__.py", line 332, in __getattr__
    submod = importlib.import_module(submod_path)
  File "importlib\__init__.py", line 126, in import_module
  File "C:\somewhere\sd.webui\system\python\lib\site-packages\huggingface_hub\hf_api.py", line 51, in <module>
    from huggingface_hub.utils import (
  File "C:\somewhere\sd.webui\system\python\lib\site-packages\huggingface_hub\utils\__init__.py", line 18, in <module>
    from . import tqdm as _tqdm  # _tqdm is the module
  File "C:\somewhere\sd.webui\system\python\lib\site-packages\huggingface_hub\utils\tqdm.py", line 63, in <module>
    from tqdm.auto import tqdm as old_tqdm
ModuleNotFoundError: No module named 'tqdm.auto'
Press any key to continue . . .
```

</p>
</details>

**Comment by alienware377** [comment]
[>216](https://github.com/kabachuha/sd-webui-text2video/issues/216) 

It wasn't exactly "fixed" in that the plugin author didn't fix the problem, but it's easily fixable by yourself by using the methods outlined in the thread linked above. 

I'm reopening this since I do think the extension author should look into fixing it. Basically the problem is just that this extension replaces your current tqdm installed version with an older one, presumably on accident, which breaks your entire auto1111 installation. 

Simply upgrading the tqdm version, or removing the extension and deleting the venv folder, letting it repopulate, backing up the tqdm folders as mentioned in the link, re-installing the extension, then replacing the newly installed old tqdm with the backup, should work to fix it regardless of whether the extension author fixes the issue on their side.

**Comment by lalanikarim** [comment]
To fix this update moviepy package and tqdm package to latest versions.
Run the following commands from within automatic1111 folder where you have `venv` sub-folder
```bash
$ source ./venv/bin/activate
$ pip install moviepy==1.0.3
$ pip install tqdm==4.66.1
```
