### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'numexpr'

### ISSUE THREAD

**Issue by helloansuman** [kabachuha/sd-webui-text2video#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

On Automatic 1111. I have downloaded the extension. 
Then after restart it is giving ModuleNotFoundError: No module named 'numexpr' error
![Uploading image.png…]()

### Steps to reproduce the problem

1. Install extension text2Video from extension tab of Automatic1111
2. RestartUI
3. You will get the above error
4. Also the text2video tab is missing

### What should have happened?

No error.

### WebUI and Deforum extension Commit IDs

webui commit id - 68f336bd994bed5442ad95bad6b6ad5564a5409a
txt2vid commit id - not available

### Torch version

'2.0.1+cu118'

### What GPU were you using for launching?

2080Ti

### On which platform are you launching the webui backend with the extension?

Local PC setup (Windows)

### Settings

![image](https://github.com/kabachuha/sd-webui-text2video/assets/5870228/ebb32775-3854-4374-908a-ec4f712f4352)

### Console logs

```Shell
*** Error loading script: api_t2v.py
    Traceback (most recent call last):
      File "D:\sd.webui\webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\sd.webui\webui\extensions\sd-webui-text2video\scripts\api_t2v.py", line 40, in <module>
        from t2v_helpers.render import run
      File "D:\sd.webui\webui/extensions/sd-webui-text2video/scripts\t2v_helpers\render.py", line 5, in <module>
        from modelscope.process_modelscope import process_modelscope
      File "D:\sd.webui\webui/extensions/sd-webui-text2video/scripts\modelscope\process_modelscope.py", line 10, in <module>
        from t2v_helpers.key_frames import T2VAnimKeys  # TODO: move to deforum_tools
      File "D:\sd.webui\webui/extensions/sd-webui-text2video/scripts\t2v_helpers\key_frames.py", line 6, in <module>
        import numexpr
    ModuleNotFoundError: No module named 'numexpr'

---
*** Error loading script: text2vid.py
    Traceback (most recent call last):
      File "D:\sd.webui\webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\sd.webui\webui\extensions\sd-webui-text2video\scripts\text2vid.py", line 24, in <module>
        from t2v_helpers.render import run
      File "D:\sd.webui\webui/extensions/sd-webui-text2video/scripts\t2v_helpers\render.py", line 5, in <module>
        from modelscope.process_modelscope import process_modelscope
      File "D:\sd.webui\webui/extensions/sd-webui-text2video/scripts\modelscope\process_modelscope.py", line 10, in <module>
        from t2v_helpers.key_frames import T2VAnimKeys  # TODO: move to deforum_tools
      File "D:\sd.webui\webui/extensions/sd-webui-text2video/scripts\t2v_helpers\key_frames.py", line 6, in <module>
        import numexpr
    ModuleNotFoundError: No module named 'numexpr'

---
```

**Comment by kabachuha** [comment]
Oh, thanks! Will add

**Comment by kabachuha** [comment]
Wait, it's already in the requirements!

https://github.com/kabachuha/sd-webui-text2video/blob/main/requirements.txt

**Comment by kabachuha** [comment]
Please, send the full log to see if it installs any requirements on startup at all

**Comment by helloansuman** [comment]
Got it thank you.
