### ISSUE TITLE
[Bug]: Tab does not appear in the extension bar at the top after installing the extension

### ISSUE THREAD

**Issue by eaizy** [kabachuha/sd-webui-text2video#232]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

When I install the extension, the tab does not appear in the extension bar. I moved all my extensions to another location and left only the text2video extension and restarted it, but it is still not visible. I have uninstalled and reinstalled many times but the problem persists. It's also shown on installed extensions tab.

### Steps to reproduce the problem

1. Go to .... Start webui
2. Press .... extensions
3. ... download from link, apply and restart UI

### What should have happened?

Extension must be visible on the top bar

### WebUI and Deforum extension Commit IDs

webui commit id - 5ef669de080814067961f28357256e8fe27544f4
txt2vid commit id - 01e41fd454c011b479c271cee33e5b5a90076ffd

### Torch version

 torch: 2.0.1+cu118

### What GPU were you using for launching?

RTX4090

### On which platform are you launching the webui backend with the extension?

Local PC setup (Windows)

### Settings

@ECHO OFF
REM BFCPEOPTIONSTART
REM Advanced BAT to EXE Converter www.BatToExeConverter.com
REM BFCPEEXE=C:\Users\TKA\Desktop\Stable Diffusion 2.exe
REM BFCPEICON=C:\Users\TKA\Downloads\196056941-aace0837-473a-4aa5-9067-505b17797aa1.ico
REM BFCPEICONINDEX=-1
REM BFCPEEMBEDDISPLAY=0
REM BFCPEEMBEDDELETE=1
REM BFCPEADMINEXE=1
REM BFCPEINVISEXE=0
REM BFCPEVERINCLUDE=0
REM BFCPEVERVERSION=1.0.0.0
REM BFCPEVERPRODUCT=Product Name
REM BFCPEVERDESC=Product Description
REM BFCPEVERCOMPANY=Your Company
REM BFCPEVERCOPYRIGHT=Copyright Info
REM BFCPEWINDOWCENTER=1
REM BFCPEDISABLEQE=1
REM BFCPEWINDOWHEIGHT=25
REM BFCPEWINDOWWIDTH=80
REM BFCPEWTITLE=Stable Diffusion
REM BFCPEOPTIONEND
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --xformers --autolaunch --opt-sdp-no-mem-attention --no-half-vae --opt-channelslast --api --update-check

call webui.bat

### Console logs

```Shell
venv "C:\AI\SSD2\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
current transparent-background 1.2.4
Installing requirements for CivitAI Browser
Installing wav2lip_uhq requirement: dlib-bin
Installing wav2lip_uhq requirement: opencv-python
Installing wav2lip_uhq requirement: pillow
Installing wav2lip_uhq requirement: librosa==0.10.0.post2
Installing wav2lip_uhq requirement: opencv-contrib-python
Installing wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git
Installing wav2lip_uhq requirement: insightface==0.7.3
Installing wav2lip_uhq requirement: onnx==1.14.0
Installing wav2lip_uhq requirement: onnxruntime==1.15.0
Installing wav2lip_uhq requirement: onnxruntime-gpu==1.15.0
Installing wav2lip_uhq requirement: opencv-python>=4.8.0
Installing sd-webui-controlnet requirement: changing opencv-python version from 4.7.0.72 to 4.8.0
Installing fastai==1.0.60 for DeOldify extension
Installing ffmpeg-python for DeOldify extension
Installing yt-dlp for DeOldify extension
Installing opencv-python for DeOldify extension
Installing Pillow for DeOldify extension
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
loading Smart Crop reqs from C:\AI\SSD2\stable-diffusion-webui\extensions\sd_smartprocess\requirements.txt
Checking Smart Crop requirements.
Installing pyqt5 requirement for depthmap script
You are up to date with the most recent release.
Launching Web UI with arguments: --xformers --autolaunch --opt-sdp-no-mem-attention --no-half-vae --opt-channelslast --api --update-check
C:\AI\SSD2\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: encv-python is an invalid version and will not be supported in a future release
  warnings.warn(

========================= a1111-sd-webui-lycoris =========================
Starting from stable-diffusion-webui version 1.5.0
a1111-sd-webui-lycoris extension is no longer needed

All its features have been integrated into the native LoRA extension
LyCORIS models can now be used as if there are regular LoRA models

This extension has been automatically deactivated
Please remove this extension
==========================================================================

Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.10.0, num models: 9
Aria2 RPC started
2023-10-11 15:29:01,613 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: C:\AI\SSD2\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-10-11 15:29:01,812 - ControlNet - INFO - ControlNet v1.1.410
*** Error loading script: api.py
    Traceback (most recent call last):
      File "C:\AI\SSD2\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\SSD2\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\SSD2\stable-diffusion-webui\extensions\sd-webui-roop\scripts\api.py", line 17, in <module>
        from scripts.faceswap import get_models
    ImportError: cannot import name 'get_models' from 'scripts.faceswap' (unknown location)

---
2023-10-11 15:29:04,979 - roop - INFO - roop v0.0.2
2023-10-11 15:29:04,981 - roop - INFO - roop v0.0.2
*** Error loading script: main.py
    Traceback (most recent call last):
      File "C:\AI\SSD2\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\SSD2\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\SSD2\stable-diffusion-webui\extensions\sd_smartprocess\scripts\main.py", line 3, in <module>
        from extensions.sd_smartprocess import smartprocess
      File "C:\AI\SSD2\stable-diffusion-webui\extensions\sd_smartprocess\smartprocess.py", line 15, in <module>
        from extensions.sd_smartprocess.clipinterrogator import ClipInterrogator
      File "C:\AI\SSD2\stable-diffusion-webui\extensions\sd_smartprocess\clipinterrogator.py", line 14, in <module>
        from models.blip import blip_decoder, BLIP_Decoder
      File "C:\AI\SSD2\stable-diffusion-webui\repositories\BLIP\models\blip.py", line 11, in <module>
        from models.vit import VisionTransformer, interpolate_pos_embed
      File "C:\AI\SSD2\stable-diffusion-webui\repositories\BLIP\models\vit.py", line 21, in <module>
        from fairscale.nn.checkpoint.checkpoint_activations import checkpoint_wrapper
    ModuleNotFoundError: No module named 'fairscale'

---
Installing pywin32
Loading weights [74dda471cc] from C:\AI\SSD2\stable-diffusion-webui\models\Stable-diffusion\realvisxlV20_v20Bakedvae.safetensors
Creating model from config: C:\AI\SSD2\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Civitai Shortcut: v1.6.7
Civitai Shortcut: shortcut update start
*Deforum ControlNet support: enabled*
INFO:root:Loaded ViT-bigG-14 model config.
Loaded ViT-bigG-14 model config.
Civitai Shortcut: shortcut update end
*** Error executing callback ui_tabs_callback for C:\AI\SSD2\stable-diffusion-webui\extensions\sd-webui-text2video\scripts\text2vid.py
    Traceback (most recent call last):
      File "C:\AI\SSD2\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "C:\AI\SSD2\stable-diffusion-webui\extensions\sd-webui-text2video\scripts\text2vid.py", line 51, in on_ui_tabs
        stable_lora_ui = StableLoraScript.ui()
      File "C:\AI\SSD2\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\stable_lora\scripts\lora_webui.py", line 53, in ui
        paths_with_metadata, lora_names = self.get_lora_files()
      File "C:\AI\SSD2\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\stable_lora\stable_utils\lora_processor.py", line 24, in get_lora_files
        with safe_open(lora_path, 'pt') as lora_file:
    safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

---
Running on local URL:  http://127.0.0.1:7860
Applying attention optimization: xformers... done.

To create a public link, set `share=True` in `launch()`.
Startup time: 155.6s (prepare environment: 110.6s, import torch: 7.2s, import gradio: 1.5s, setup paths: 0.7s, initialize shared: 0.2s, other imports: 1.8s, setup codeformer: 0.6s, load scripts: 25.2s, create ui: 4.5s, gradio launch: 3.0s, app_started_callback: 0.1s).
Model loaded in 8.2s (load weights from disk: 1.2s, create model: 0.9s, apply weights to model: 4.8s, calculate empty prompt: 1.0s).
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
```

### Additional information

![Ekran görüntüsü 2023-10-11 153423](https://github.com/kabachuha/sd-webui-text2video/assets/117603545/04f55618-f6d4-4824-b3bf-4b23348a272c)

**Comment by plaidpants** [comment]
same issue, appears to be changes in A1111 broke txt2vid, maybe due to sdxl support or some other change, the settings tab is present however but no txt2vid tab.

T:\stable-diffusion-webui5\extensions\sd-webui-text2video\scripts\text2vid.py:48: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row(elem_id='t2v-core').style(equal_height=False, variant='compact'):
Creating model from config: T:\stable-diffusion-webui5\repositories\generative-models\configs\inference\sd_xl_base.yaml
*** Error executing callback ui_tabs_callback for T:\stable-diffusion-webui5\extensions\sd-webui-text2video\scripts\text2vid.py
    Traceback (most recent call last):
      File "T:\stable-diffusion-webui5\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
               ^^^^^^^^^^^^
      File "T:\stable-diffusion-webui5\extensions\sd-webui-text2video\scripts\text2vid.py", line 51, in on_ui_tabs
        stable_lora_ui = StableLoraScript.ui()
                         ^^^^^^^^^^^^^^^^^^^^^
      File "T:\stable-diffusion-webui5/extensions/sd-webui-text2video/scripts\stable_lora\scripts\lora_webui.py", line 53, in ui
        paths_with_metadata, lora_names = self.get_lora_files()
                                          ^^^^^^^^^^^^^^^^^^^^^
      File "T:\stable-diffusion-webui5/extensions/sd-webui-text2video/scripts\stable_lora\stable_utils\lora_processor.py", line 24, in get_lora_files
        with safe_open(lora_path, 'pt') as lora_file:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

---
Running on local URL:  http://127.0.0.1:7860

**Comment by adamflorizone** [comment]
Same here:

using 01e41fd
webui version: v1.6.0  •  python: 3.10.9  •  torch: 2.0.1+cu118  •  xformers: 0.0.21.dev544  •  gradio: 3.41.2

```
*** Error executing callback ui_tabs_callback for /stable-diffusion-webui/extensions-builtin/sd-webui-text2video.git/scripts/text2vid.py
    Traceback (most recent call last):
      File "/stable-diffusion-webui/modules/script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "/stable-diffusion-webui/extensions-builtin/sd-webui-text2video.git/scripts/text2vid.py", line 51, in on_ui_tabs
        stable_lora_ui = StableLoraScript.ui()
      File "/stable-diffusion-webui/extensions-builtin/sd-webui-text2video.git/scripts/stable_lora/scripts/lora_webui.py", line 53, in ui
        paths_with_metadata, lora_names = self.get_lora_files()
      File "/stable-diffusion-webui/extensions-builtin/sd-webui-text2video.git/scripts/stable_lora/stable_utils/lora_processor.py", line 24, in get_lora_files
        with safe_open(lora_path, 'pt') as lora_file:
    safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
```
