### ISSUE TITLE
[Bug]: Lora error: Exception occurred: No such file or directory:

### ISSUE THREAD

**Issue by imminentarchon** [kabachuha/sd-webui-text2video#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

I receive an error every time I attempt to use a LoRA model in the webui. It was trained using the Text-to-Video-Finetuning repo.

### Steps to reproduce the problem

1. Copy LoRA to stable-diffusion-webui Lora folder as instructed.
2. Select the Stable LoRA model in txt2video.
3. Attempt generating.

### What should have happened?

The video should have been generated using the LoRA.

### WebUI and Deforum extension Commit IDs

webui commit id - [447faa5248](https://google.com/search?q=447faa52485e11648871312f155048f0e9a153de47a20e395af6f9cb0bfc8094)
txt2vid commit id - [01e41fd4](https://github.com/kabachuha/sd-webui-text2video/commit/01e41fd454c011b479c271cee33e5b5a90076ffd)

### Torch version

2.1.0

### What GPU were you using for launching?

RTX 3090, 24GB

### On which platform are you launching the webui backend with the extension?

Local PC setup (Windows)

### Settings

![image](https://github.com/kabachuha/sd-webui-text2video/assets/74319654/b16c1eb4-ec8a-462f-b1ec-6ec508b414e2)

### Console logs

```Shell
Git commit: 01e41fd4
Starting text2video
Pipeline setup
config namespace(framework='pytorch', task='text-to-video-synthesis', model={'type': 'latent-text-to-video-synthesis', 'model_args': {'ckpt_clip': 'open_clip_pytorch_model.bin', 'ckpt_unet': 'text2video_pytorch_model.pth', 'ckpt_autoencoder': 'VQGAN_autoencoder.pth', 'max_frames': 16, 'tiny_gpu': 1}, 'model_cfg': {'unet_in_dim': 4, 'unet_dim': 320, 'unet_y_dim': 768, 'unet_context_dim': 1024, 'unet_out_dim': 4, 'unet_dim_mult': [1, 2, 4, 4], 'unet_num_heads': 8, 'unet_head_dim': 64, 'unet_res_blocks': 2, 'unet_attn_scales': [1, 0.5, 0.25], 'unet_dropout': 0.1, 'temporal_attention': 'True', 'num_timesteps': 1000, 'mean_type': 'eps', 'var_type': 'fixed_small', 'loss_type': 'mse'}}, pipeline={'type': 'latent-text-to-video-synthesis'})
Traceback (most recent call last):
  File "C:\Users\redacted\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\t2v_helpers\render.py", line 30, in run
    vids_pack = process_modelscope(args_dict, args)
  File "C:\Users\redacted\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\modelscope\process_modelscope.py", line 71, in process_modelscope
    stable_lora_processor.process(pipe, *stable_lora_args)
  File "C:\Users\redacted\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\redacted\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\stable_lora\scripts\lora_webui.py", line 190, in process
    lora_files_list = self.load_loras_from_list(lora_files)
  File "C:\Users\redacted\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\stable_lora\stable_utils\lora_processor.py", line 169, in load_loras_from_list
    lora_model = load_method(LORA_PATH)
  File "C:\Users\redacted\stable-diffusion-webui\venv\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
FileNotFoundError: No such file or directory: "C:\\Users\\redacted\\stable-diffusion-webui\\models\\Lora/C:\\Users\\redacted\\stable-diffusion-webui\\models\\Lora\\webui_10000_lora_text_to_video.safetensors"
Exception occurred: No such file or directory: "C:\\Users\\redacted\\stable-diffusion-webui\\models\\Lora/C:\\Users\\redacted\\stable-diffusion-webui\\models\\Lora\\webui_10000_lora_text_to_video.safetensors"
```

**Comment by 23Rj20** [comment]
Did you figure out how to correct this error??
